import '../services/language_service.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _t = {
    'en': {
      'incorrect_credentials': 'Incorrect email or password. Please try again.',
      'token_save_error': 'Could not save the token.',
      'forgot_sent': 'We sent a password reset link to your email address.',
      'forgot_fail': 'We could not send the link. Please try again.',
      'forgot_description':
          'No problem. Enter your email and we will send you a password reset link.',
      'forgot_submit': 'Email Password Reset Link',
      'categories_load_fail':
          'Could not load the categories. Please try again.',
      'create_fail': 'Could not create the report. Please try again.',
      'load_reports_fail': 'Could not load the reports. Please try again.',
      'name_save_fail': 'Could not save the name. Please try again.',
      'verification_sent': 'Verification link sent. Check your new email.',
      'verification_failed':
          'Could not send the verification email. Please try again.',
      'email_change_requested':
          'Confirmation email sent. Check your new email address.',
      'email_change_failed':
          'Could not request the email change. Please try again.',
      'password_changed': 'Password updated successfully.',
      'password_change_failed':
          'Could not change the password. Please try again.',
      'no_data_available': 'No data available',
      'app_name': 'LookCrim',
      'welcome': 'Welcome',
      'login_to_continue': 'Login to continue',
      'access': 'Access',
      'use_email_password': 'Use your email and password',
      'email_address': 'Email address',
      'email_required': 'Email is required',
      'valid_email': 'Please enter a valid email',
      'password': 'Password',
      'password_required': 'Password is required',
      'password_min_length': 'Password must be at least 6 characters',
      'login': 'Login',
      'forgot_password': 'Forgot your Password?',
      'camera': 'Camera',
      'files': 'Files',
      'selected_location': 'Selected location',
      'select_category': 'Select a category',
      'select_image': 'Select an image',
      'create_register_title': 'CREATE REGISTER',
      'title': 'Title',
      'set_title_to_register': 'Set title to register',
      'category': 'Category',
      'tap_select_category': 'Tap to select category',
      'set_category': 'Set Category',
      'images': 'Images',
      'image': 'Image',
      'add_images': 'Add Images',
      'content': 'Content',
      'details_of_incident': 'Details of Incident',
      'edit_location': 'Edit Location',
      'set_location': 'Set location',
      'create_register': 'Create Register',
      'city_area': 'City area',
      'current_location': 'Current location',
      'location_services_disabled': 'Location services are disabled.',
      'location_permission_denied': 'Location permission denied.',
      'location_permission_denied_forever':
          'Location permission permanently denied.',
      'unable_get_current_location': 'Unable to get current location.',
      'your_location': 'Your location',
      'your_location_title': 'Your Location',
      'read_register': 'Read Register',
      'author': 'Author',
      'date': 'Date',
      'description': 'Description',
      'show_less': 'Show less',
      'read_more': 'Read more',
      'map_not_available': 'Map not available',
      'location': 'Location',
      'export_register': 'Export Register',
      'na': 'N/A',
      'untitled': 'Untitled',
      'unknown': 'Unknown',
      'no_description': 'No description',
      'error_loading_register': 'Error loading register:\n',
      'logout_account': 'Logout Account',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'logout': 'Logout',
      'logout_account_short': 'Log out account',
      'personal_info': 'Personal Info',
      'user_name': 'User Name',
      'email': 'Email',
      'role': 'Role',
      'city': 'City',
      'edit_name': 'Edit Name',
      'current_name': 'Current Name',
      'new_name': 'New Name',
      'save_edit': 'Save edit',
      'name_required': 'Name cannot be empty.',
      'name_updated': 'Name updated successfully.',
      'fill_all_fields': 'Please complete all fields.',
      'change_email': 'Change Email',
      'current_email': 'Current Email',
      'current_password': 'Current Password',
      'new_email': 'New Email',
      'send_confirmation_email': 'Send confirmation email',
      'change_password': 'Change Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'save_password': 'Save password',
      'passwords_no_match': 'Passwords do not match.',
      'password_min_8': 'The new password must be at least 8 characters.',
      'sign_out': 'Sign out',
      'profile': 'Profile',
      'error_loading_user': 'Error loading user:\n',
      'app_language': 'App language',
      'english': 'English',
      'portuguese_pt': 'Português (PT)',
      'search': 'Search',
      'create_new_register': 'Create New Register',
      'location_not_available': 'Location not available',
      'language_dialog_title': 'Language information',
      'language_dialog_message_profile':
          'The app is currently in {lang}. To change the app language, go to your Profile.',
      'go_to_profile': 'Go to Profile',
      'download': 'Download',
      'map_downloads': 'Map downloads',
      'map_downloads_description': 'Offline areas outside your city.',
      'map_downloads_hint':
          'Move and zoom the map, then download the visible area with a little extra margin for offline use.',
      'download_started': 'Download started',
      'download_started_title': 'Download started',
      'download_started_message':
          'The map download has started in the background. You can keep using the app while it finishes.',
      'download_finished_title': 'Download finished',
      'download_finished_message':
          'The download for {area} is complete and ready for offline use.',
      'download_failed_title': 'Download failed',
      'map_downloads_load_failed':
          'Could not open map downloads. Please try again.',
      'map_downloads_invalid_values':
          'Please enter valid map coordinates and zoom values.',
      'download_city_area': 'Download city area',
      'download_city_area_description':
          'Download the full city coverage used by the app as a quick offline area.',
      'download_default_area': 'Download default area',
      'download_custom_area': 'Download custom area',
      'download_custom_area_description':
          'Choose another area, even outside your city, without changing the default map area.',
      'download_this_area': 'Download this area',
      'download_this_area_description':
          'This downloads the area currently visible on the map, with a little extra coverage for offline use.',
      'visible_map_area': 'visible map area',
      'center_latitude': 'Center latitude',
      'center_longitude': 'Center longitude',
      'radius_meters': 'Radius in meters',
      'min_zoom': 'Min zoom',
      'max_zoom': 'Max zoom',
      'map_downloads_started': 'Map download started for',
      'map_downloads_failed': 'Map download failed:',
      'map_downloads_cached': 'Map data cached for offline use.',
      'map_downloads_cache_failed': 'Could not cache map data for offline use.',
      'ok': 'OK',
      'edit': 'Edit',
      'delete': 'Delete',
      'delete_register': 'Delete Register',
      'delete_register_confirm':
          'Are you sure you want to delete this register? This action cannot be undone.',
      'delete_register_success': 'Register deleted successfully.',
      'delete_register_failed':
          'Could not delete the register. Please try again.',
      'no_permission_for_action':
          'You do not have permission to perform this action.',
      'edit_register': 'Edit Register',
      'save_changes': 'Save Changes',
      'edit_images': 'Edit Images',
      'add_image': 'Add Image',
      'remove_image': 'Remove image',
      'map_default_area': 'Map default area',
      'map_default_area_description':
          'Move and zoom the map to choose your default working area.',
      'city_default_area': 'City default area',
      'custom_area': 'Custom area',
      'preview_city_default': 'Preview city default',
      'save_custom_area': 'Save custom area',
      'use_city_default': 'Use city default',
      'map_default_saved': 'Custom map area saved.',
      'map_default_reset_city': 'Map area reset to city default.',
      'map_default_load_failed':
          'Could not load city map settings. Please try again.',
      'map_default_city_unavailable':
          'City center is not available for this user.',
      'recenter_map': 'Recenter map',
      'offline_missing_categories':
          'Offline mode is not ready yet. Categories are not cached.',
      'offline_missing_user_context':
          'Offline mode is not ready yet. City settings are not cached.',
      'offline_missing_register_cache':
          'Offline mode is not ready yet. Recent registers are not cached.',
      'offline_db_error':
          'Offline mode could not read local data. Please try again.',
      'offline_blocked_title': 'No internet connection',
      'offline_blocked_message':
          'The app cannot continue offline because the required data is not available yet. Please try again when you have internet.',
      'offline_only_profile_message':
          'This section is not available without internet. Please try again later.',
      'pending_register_saved':
          'Register saved locally and will be uploaded when internet is available.',
      'pending_register_sync_started': 'Uploading pending registers...',
      'pending_register_sync_done': 'Pending registers uploaded successfully.',
      'pending_register_sync_failed':
          'Some pending registers could not be uploaded yet.',
      'image_too_large':
          'Selected image is too large. Please choose a smaller image (<2.5MB).',
      'pending_cancelled': 'Pending register cancelled.',
      'sync_pending': 'Sync pending',
      'pending_registers': 'Pending registers',
      'no_pending_registers': 'No pending registers',
      'no_pending_registers_message':
          'Offline or delayed reports will appear here.',
      'pending_short': 'Pending',
      'pending_status_waiting_internet': 'Waiting for internet',
      'pending_status_resolving_address': 'Resolving address',
      'pending_status_waiting_upload': 'Ready to upload',
      'upload_registers': 'Upload registers',
      'retry_upload': 'Retry',
      'pending_synced_success': 'Pending registers uploaded successfully.',
      'pending_synced_nothing': 'No pending registers to upload.',
      'pending_synced_success_single': 'Pending register uploaded.',
      'pending_synced_failed_single':
          'Could not upload the pending register yet.',
    },
    'pt': {
      'incorrect_credentials': 'Email ou senha incorretos. Tente novamente.',
      'token_save_error': 'Não foi possível salvar o token.',
      'forgot_sent': 'Enviamos um link para redefinir a senha para seu e-mail.',
      'forgot_fail': 'Não foi possível enviar o link. Tente novamente.',
      'forgot_description':
          'Sem problema. Digite seu e-mail e enviaremos um link para redefinir a senha.',
      'forgot_submit': 'Enviar link de redefinição',
      'categories_load_fail':
          'Não foi possível carregar as categorias. Tente novamente.',
      'create_fail': 'Não foi possível criar o relatório. Tente novamente.',
      'load_reports_fail':
          'Não foi possível carregar os relatórios. Tente novamente.',
      'name_save_fail': 'Não foi possível salvar o nome. Tente novamente.',
      'verification_sent':
          'Link de verificação enviado. Verifique seu novo e-mail.',
      'verification_failed':
          'Não foi possível enviar o e-mail de verificação. Tente novamente.',
      'email_change_requested':
          'E-mail de confirmação enviado. Verifique seu novo e-mail.',
      'email_change_failed':
          'Não foi possível solicitar a alteração de e-mail. Tente novamente.',
      'password_changed': 'Senha atualizada com sucesso.',
      'password_change_failed':
          'Não foi possível alterar a senha. Tente novamente.',
      'no_data_available': 'Nenhum dado disponível',
      'app_name': 'LookCrim',
      'welcome': 'Bem-vindo',
      'login_to_continue': 'Faça login para continuar',
      'access': 'Acesso',
      'use_email_password': 'Use seu e-mail e senha',
      'email_address': 'Endereço de e-mail',
      'email_required': 'O e-mail é obrigatório',
      'valid_email': 'Digite um e-mail válido',
      'password': 'Senha',
      'password_required': 'A senha é obrigatória',
      'password_min_length': 'A senha deve ter pelo menos 6 caracteres',
      'login': 'Entrar',
      'forgot_password': 'Esqueceu sua senha?',
      'camera': 'Câmera',
      'files': 'Arquivos',
      'selected_location': 'Localização selecionada',
      'select_category': 'Selecione uma categoria',
      'select_image': 'Selecione uma imagem',
      'create_register_title': 'CRIAR REGISTRO',
      'title': 'Título',
      'set_title_to_register': 'Defina o título do registro',
      'category': 'Categoria',
      'tap_select_category': 'Toque para selecionar a categoria',
      'set_category': 'Definir categoria',
      'images': 'Imagens',
      'image': 'Imagem',
      'add_images': 'Adicionar imagens',
      'content': 'Conteúdo',
      'details_of_incident': 'Detalhes do incidente',
      'edit_location': 'Editar localização',
      'set_location': 'Definir localização',
      'create_register': 'Criar registro',
      'city_area': 'Área da cidade',
      'current_location': 'Localização atual',
      'location_services_disabled':
          'Os serviços de localização estão desativados.',
      'location_permission_denied': 'Permissão de localização negada.',
      'location_permission_denied_forever':
          'Permissão de localização negada permanentemente.',
      'unable_get_current_location':
          'Não foi possível obter a localização atual.',
      'your_location': 'Sua localização',
      'your_location_title': 'Sua Localização',
      'read_register': 'Ler registro',
      'author': 'Autor',
      'date': 'Data',
      'description': 'Descrição',
      'show_less': 'Mostrar menos',
      'read_more': 'Ler mais',
      'map_not_available': 'Mapa indisponível',
      'location': 'Localização',
      'export_register': 'Exportar registro',
      'na': 'N/D',
      'untitled': 'Sem título',
      'unknown': 'Desconhecido',
      'no_description': 'Sem descrição',
      'error_loading_register': 'Erro ao carregar o registro:\n',
      'logout_account': 'Sair da conta',
      'logout_confirm': 'Tem certeza de que deseja sair?',
      'cancel': 'Cancelar',
      'logout': 'Sair',
      'logout_account_short': 'Sair da conta',
      'personal_info': 'Informações pessoais',
      'user_name': 'Nome de usuário',
      'email': 'E-mail',
      'role': 'Função',
      'city': 'Cidade',
      'edit_name': 'Editar nome',
      'current_name': 'Nome atual',
      'new_name': 'Novo nome',
      'save_edit': 'Salvar edição',
      'name_required': 'O nome não pode estar vazio.',
      'name_updated': 'Nome atualizado com sucesso.',
      'fill_all_fields': 'Preencha todos os campos.',
      'change_email': 'Alterar e-mail',
      'current_email': 'E-mail atual',
      'current_password': 'Senha atual',
      'new_email': 'Novo e-mail',
      'send_confirmation_email': 'Enviar e-mail de confirmação',
      'change_password': 'Alterar senha',
      'new_password': 'Nova senha',
      'confirm_password': 'Confirmar senha',
      'save_password': 'Salvar senha',
      'passwords_no_match': 'As senhas não coincidem.',
      'password_min_8': 'A nova senha deve ter pelo menos 8 caracteres.',
      'sign_out': 'Sair',
      'profile': 'Perfil',
      'error_loading_user': 'Erro ao carregar o usuário:\n',
      'app_language': 'Idioma do app',
      'english': 'English',
      'portuguese_pt': 'Português (PT)',
      'search': 'Pesquisar',
      'create_new_register': 'Criar novo registo',
      'location_not_available': 'Localização indisponível',
      'language_dialog_title': 'Informação de idioma',
      'language_dialog_message_profile':
          'O aplicativo está em {lang}. Para alterar o idioma, vá para Perfil.',
      'go_to_profile': 'Ir para Perfil',
      'download': 'Baixar',
      'map_downloads': 'Downloads do mapa',
      'map_downloads_description': 'Áreas offline fora da sua cidade.',
      'map_downloads_hint':
          'Mova e aproxime o mapa e depois baixe a área visível com uma pequena margem extra para uso offline.',
      'download_started': 'Download iniciado',
      'download_started_title': 'Download iniciado',
      'download_started_message':
          'O download do mapa começou em segundo plano. Você pode continuar usando o app enquanto ele termina.',
      'download_finished_title': 'Download concluído',
      'download_finished_message':
          'O download de {area} foi concluído e já está pronto para uso offline.',
      'download_failed_title': 'Falha no download',
      'map_downloads_load_failed':
          'Não foi possível abrir os downloads do mapa. Tente novamente.',
      'map_downloads_invalid_values':
          'Digite coordenadas e níveis de zoom válidos.',
      'download_city_area': 'Baixar área da cidade',
      'download_city_area_description':
          'Baixe a cobertura completa da cidade usada pelo aplicativo como área offline rápida.',
      'download_default_area': 'Baixar área padrão',
      'download_custom_area': 'Baixar área personalizada',
      'download_custom_area_description':
          'Escolha outra área, até fora da sua cidade, sem alterar a área padrão do mapa.',
      'download_this_area': 'Baixar esta área',
      'download_this_area_description':
          'Isso baixa a área visível no mapa, com uma pequena cobertura extra para uso offline.',
      'visible_map_area': 'área visível do mapa',
      'center_latitude': 'Latitude do centro',
      'center_longitude': 'Longitude do centro',
      'radius_meters': 'Raio em metros',
      'min_zoom': 'Zoom mín.',
      'max_zoom': 'Zoom máx.',
      'map_downloads_started': 'Download do mapa iniciado para',
      'map_downloads_failed': 'Falha no download do mapa:',
      'map_downloads_cached': 'Dados do mapa em cache para uso offline.',
      'map_downloads_cache_failed':
          'Não foi possível armazenar em cache os dados do mapa para uso offline.',
      'ok': 'OK',
      'edit': 'Editar',
      'delete': 'Excluir',
      'delete_register': 'Excluir registro',
      'delete_register_confirm':
          'Tem certeza de que deseja excluir este registro? Esta ação não pode ser desfeita.',
      'delete_register_success': 'Registro excluído com sucesso.',
      'delete_register_failed':
          'Não foi possível excluir o registro. Tente novamente.',
      'no_permission_for_action':
          'Você não tem permissão para executar esta ação.',
      'edit_register': 'Editar registro',
      'save_changes': 'Salvar alterações',
      'edit_images': 'Editar imagens',
      'add_image': 'Adicionar imagem',
      'remove_image': 'Remover imagem',
      'map_default_area': 'Area padrao do mapa',
      'map_default_area_description':
          'Mova e ajuste o zoom do mapa para definir sua area padrao de trabalho.',
      'city_default_area': 'Area padrao da cidade',
      'custom_area': 'Area personalizada',
      'preview_city_default': 'Ver area da cidade',
      'save_custom_area': 'Salvar area personalizada',
      'use_city_default': 'Usar area da cidade',
      'map_default_saved': 'Area personalizada do mapa salva.',
      'map_default_reset_city':
          'Area do mapa redefinida para o padrao da cidade.',
      'map_default_load_failed':
          'Nao foi possivel carregar as configuracoes do mapa da cidade. Tente novamente.',
      'map_default_city_unavailable':
          'Centro da cidade indisponivel para este usuario.',
      'recenter_map': 'Recentralizar mapa',
      'offline_missing_categories':
          'O modo offline ainda não está pronto. As categorias não estão salvas.',
      'offline_missing_user_context':
          'O modo offline ainda não está pronto. As configurações da cidade não estão salvas.',
      'offline_missing_register_cache':
          'O modo offline ainda não está pronto. Os registros recentes não estão salvas.',
      'offline_db_error':
          'O modo offline não conseguiu ler os dados locais. Tente novamente.',
      'offline_blocked_title': 'Sem conexão com a internet',
      'offline_blocked_message':
          'O aplicativo não pode continuar sem internet porque os dados mínimos ainda não estão disponíveis. Tente novamente quando tiver conexão.',
      'offline_only_profile_message':
          'Esta seção não está disponível sem internet. Tente novamente mais tarde.',
      'pending_register_saved':
          'Registro salvo localmente e será enviado quando houver internet.',
      'pending_register_sync_started': 'Enviando registros pendentes...',
      'pending_register_sync_done': 'Registros pendentes enviados com sucesso.',
      'pending_register_sync_failed':
          'Alguns registros pendentes ainda não puderam ser enviados.',
      'image_too_large':
          'A imagem selecionada é muito grande. Escolha uma imagem menor (<2.5MB).',
      'pending_cancelled': 'Registro pendente cancelado.',
      'sync_pending': 'Sincronizar pendentes',
      'pending_registers': 'Registros pendentes',
      'no_pending_registers': 'Sem registros pendentes',
      'no_pending_registers_message':
          'Registros offline ou aguardando envio aparecerão aqui.',
      'pending_short': 'Pendente',
      'pending_status_waiting_internet': 'Aguardando internet',
      'pending_status_resolving_address': 'Resolvendo endereço',
      'pending_status_waiting_upload': 'Pronto para enviar',
      'upload_registers': 'Enviar registros',
      'retry_upload': 'Tentar',
      'pending_synced_success': 'Registros pendentes enviados com sucesso.',
      'pending_synced_nothing': 'Não há registros pendentes para enviar.',
      'pending_synced_success_single': 'Registro pendente enviado.',
      'pending_synced_failed_single':
          'Não foi possível enviar o registro pendente ainda.',
    },
  };

  static String t(String key, {Map<String, String>? args}) {
    final code = LanguageService.instance.currentLocale.languageCode;
    final map = _t[code] ?? _t['en']!;
    var val = map[key] ?? _t['en']![key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        val = val.replaceAll('{$k}', v);
      });
    }
    return val;
  }
}
