import '../services/language_service.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _t = {
    'en': {
      'incorrect_credentials': 'Incorrect email or password. Please try again.',
      'token_save_error': 'Could not save the token.',
      'forgot_sent': 'We sent a password reset link to your email address.',
      'forgot_fail': 'We could not send the link. Please try again.',
      'forgot_description':
          'No problem. Enter your email and we will send you a password reset link.',
      'forgot_submit': 'Email Password Reset Link',
      'categories_load_fail':
          'Could not load the categories. Please try again.',
      'create_fail': 'Could not create the report. Please try again.',
      'load_reports_fail': 'Could not load the reports. Please try again.',
      'name_save_fail': 'Could not save the name. Please try again.',
      'verification_sent': 'Verification link sent. Check your new email.',
      'verification_failed':
          'Could not send the verification email. Please try again.',
      'password_changed': 'Password updated successfully.',
      'password_change_failed':
          'Could not change the password. Please try again.',
      'no_data_available': 'No data available',
      'app_name': 'LookCrim',
      'welcome': 'Welcome',
      'login_to_continue': 'Login to continue',
      'access': 'Access',
      'use_email_password': 'Use your email and password',
      'email_address': 'Email address',
      'email_required': 'Email is required',
      'valid_email': 'Please enter a valid email',
      'password': 'Password',
      'password_required': 'Password is required',
      'password_min_length': 'Password must be at least 6 characters',
      'login': 'Login',
      'forgot_password': 'Forgot your Password?',
      'camera': 'Camera',
      'files': 'Files',
      'selected_location': 'Selected location',
      'select_category': 'Select a category',
      'select_image': 'Select an image',
      'create_register_title': 'CREATE REGISTER',
      'title': 'Title',
      'set_title_to_register': 'Set title to register',
      'category': 'Category',
      'tap_select_category': 'Tap to select category',
      'set_category': 'Set Category',
      'images': 'Images',
      'image': 'Image',
      'add_images': 'Add Images',
      'content': 'Content',
      'details_of_incident': 'Details of Incident',
      'edit_location': 'Edit Location',
      'set_location': 'Set location',
      'create_register': 'Create Register',
      'city_area': 'City area',
      'current_location': 'Current location',
      'location_services_disabled': 'Location services are disabled.',
      'location_permission_denied': 'Location permission denied.',
      'location_permission_denied_forever':
          'Location permission permanently denied.',
      'unable_get_current_location': 'Unable to get current location.',
      'your_location': 'Your location',
      'your_location_title': 'Your Location',
      'read_register': 'Read Register',
      'author': 'Author',
      'date': 'Date',
      'description': 'Description',
      'show_less': 'Show less',
      'read_more': 'Read more',
      'map_not_available': 'Map not available',
      'location': 'Location',
      'export_register': 'Export Register',
      'na': 'N/A',
      'untitled': 'Untitled',
      'unknown': 'Unknown',
      'no_description': 'No description',
      'error_loading_register': 'Error loading register:\n',
      'logout_account': 'Logout Account',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'logout': 'Logout',
      'logout_account_short': 'Log out account',
      'personal_info': 'Personal Info',
      'user_name': 'User Name',
      'email': 'Email',
      'role': 'Role',
      'city': 'City',
      'edit_name': 'Edit Name',
      'current_name': 'Current Name',
      'new_name': 'New Name',
      'save_edit': 'Save edit',
      'name_required': 'Name cannot be empty.',
      'name_updated': 'Name updated successfully.',
      'fill_all_fields': 'Please complete all fields.',
      'change_email': 'Change Email',
      'current_email': 'Current Email',
      'current_password': 'Current Password',
      'new_email': 'New Email',
      'send_confirmation_email': 'Send confirmation email',
      'change_password': 'Change Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'save_password': 'Save password',
      'passwords_no_match': 'Passwords do not match.',
      'password_min_8': 'The new password must be at least 8 characters.',
      'sign_out': 'Sign out',
      'profile': 'Profile',
      'error_loading_user': 'Error loading user:\n',
      'app_language': 'App language',
      'english': 'English',
      'portuguese_pt': 'Português (PT)',
      'search': 'Search',
      'create_new_register': 'Create New Register',
      'location_not_available': 'Location not available',
      'language_dialog_title': 'Language information',
      'language_dialog_message_profile':
          'The app is currently in {lang}. To change the app language, go to your Profile.',
      'go_to_profile': 'Go to Profile',
      'ok': 'OK',
      'edit': 'Edit',
    },
    'pt': {
      'incorrect_credentials': 'Email ou senha incorretos. Tente novamente.',
      'token_save_error': 'Não foi possível salvar o token.',
      'forgot_sent': 'Enviamos um link para redefinir a senha para seu e-mail.',
      'forgot_fail': 'Não foi possível enviar o link. Tente novamente.',
      'forgot_description':
          'Sem problema. Digite seu e-mail e enviaremos um link para redefinir a senha.',
      'forgot_submit': 'Enviar link de redefinição',
      'categories_load_fail':
          'Não foi possível carregar as categorias. Tente novamente.',
      'create_fail': 'Não foi possível criar o relatório. Tente novamente.',
      'load_reports_fail':
          'Não foi possível carregar os relatórios. Tente novamente.',
      'name_save_fail': 'Não foi possível salvar o nome. Tente novamente.',
      'verification_sent':
          'Link de verificação enviado. Verifique seu novo e-mail.',
      'verification_failed':
          'Não foi possível enviar o e-mail de verificação. Tente novamente.',
      'password_changed': 'Senha atualizada com sucesso.',
      'password_change_failed':
          'Não foi possível alterar a senha. Tente novamente.',
      'no_data_available': 'Nenhum dado disponível',
      'app_name': 'LookCrim',
      'welcome': 'Bem-vindo',
      'login_to_continue': 'Faça login para continuar',
      'access': 'Acesso',
      'use_email_password': 'Use seu e-mail e senha',
      'email_address': 'Endereço de e-mail',
      'email_required': 'O e-mail é obrigatório',
      'valid_email': 'Digite um e-mail válido',
      'password': 'Senha',
      'password_required': 'A senha é obrigatória',
      'password_min_length': 'A senha deve ter pelo menos 6 caracteres',
      'login': 'Entrar',
      'forgot_password': 'Esqueceu sua senha?',
      'camera': 'Câmera',
      'files': 'Arquivos',
      'selected_location': 'Localização selecionada',
      'select_category': 'Selecione uma categoria',
      'select_image': 'Selecione uma imagem',
      'create_register_title': 'CRIAR REGISTRO',
      'title': 'Título',
      'set_title_to_register': 'Defina o título do registro',
      'category': 'Categoria',
      'tap_select_category': 'Toque para selecionar a categoria',
      'set_category': 'Definir categoria',
      'images': 'Imagens',
      'image': 'Imagem',
      'add_images': 'Adicionar imagens',
      'content': 'Conteúdo',
      'details_of_incident': 'Detalhes do incidente',
      'edit_location': 'Editar localização',
      'set_location': 'Definir localização',
      'create_register': 'Criar registro',
      'city_area': 'Área da cidade',
      'current_location': 'Localização atual',
      'location_services_disabled':
          'Os serviços de localização estão desativados.',
      'location_permission_denied': 'Permissão de localização negada.',
      'location_permission_denied_forever':
          'Permissão de localização negada permanentemente.',
      'unable_get_current_location':
          'Não foi possível obter a localização atual.',
      'your_location': 'Sua localização',
      'your_location_title': 'Sua Localização',
      'read_register': 'Ler registro',
      'author': 'Autor',
      'date': 'Data',
      'description': 'Descrição',
      'show_less': 'Mostrar menos',
      'read_more': 'Ler mais',
      'map_not_available': 'Mapa indisponível',
      'location': 'Localização',
      'export_register': 'Exportar registro',
      'na': 'N/D',
      'untitled': 'Sem título',
      'unknown': 'Desconhecido',
      'no_description': 'Sem descrição',
      'error_loading_register': 'Erro ao carregar o registro:\n',
      'logout_account': 'Sair da conta',
      'logout_confirm': 'Tem certeza de que deseja sair?',
      'cancel': 'Cancelar',
      'logout': 'Sair',
      'logout_account_short': 'Sair da conta',
      'personal_info': 'Informações pessoais',
      'user_name': 'Nome de usuário',
      'email': 'E-mail',
      'role': 'Função',
      'city': 'Cidade',
      'edit_name': 'Editar nome',
      'current_name': 'Nome atual',
      'new_name': 'Novo nome',
      'save_edit': 'Salvar edição',
      'name_required': 'O nome não pode estar vazio.',
      'name_updated': 'Nome atualizado com sucesso.',
      'fill_all_fields': 'Preencha todos os campos.',
      'change_email': 'Alterar e-mail',
      'current_email': 'E-mail atual',
      'current_password': 'Senha atual',
      'new_email': 'Novo e-mail',
      'send_confirmation_email': 'Enviar e-mail de confirmação',
      'change_password': 'Alterar senha',
      'new_password': 'Nova senha',
      'confirm_password': 'Confirmar senha',
      'save_password': 'Salvar senha',
      'passwords_no_match': 'As senhas não coincidem.',
      'password_min_8': 'A nova senha deve ter pelo menos 8 caracteres.',
      'sign_out': 'Sair',
      'profile': 'Perfil',
      'error_loading_user': 'Erro ao carregar o usuário:\n',
      'app_language': 'Idioma do app',
      'english': 'English',
      'portuguese_pt': 'Português (PT)',
      'search': 'Pesquisar',
      'create_new_register': 'Criar novo registo',
      'location_not_available': 'Localização indisponível',
      'language_dialog_title': 'Informação de idioma',
      'language_dialog_message_profile':
          'O aplicativo está em {lang}. Para alterar o idioma, vá para Perfil.',
      'go_to_profile': 'Ir para Perfil',
      'ok': 'OK',
      'edit': 'Editar',
    },
  };

  static String t(String key, {Map<String, String>? args}) {
    final code = LanguageService.instance.currentLocale.languageCode;
    final map = _t[code] ?? _t['en']!;
    var val = map[key] ?? _t['en']![key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        val = val.replaceAll('{$k}', v);
      });
    }
    return val;
  }
}
